# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dbox}
  s.version = "0.4.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Ken Pratt}]
  s.date = %q{2011-05-19}
  s.description = %q{An easy-to-use Dropbox client with fine-grained control over syncs.}
  s.email = %q{ken@kenpratt.net}
  s.executables = [%q{dbox}]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "TODO.txt",
    "VERSION",
    "bin/dbox",
    "dbox.gemspec",
    "lib/dbox.rb",
    "lib/dbox/api.rb",
    "lib/dbox/db.rb",
    "lib/dbox/loggable.rb",
    "spec/dbox_spec.rb",
    "spec/spec_helper.rb",
    "vendor/dropbox-client-ruby/LICENSE",
    "vendor/dropbox-client-ruby/README",
    "vendor/dropbox-client-ruby/Rakefile",
    "vendor/dropbox-client-ruby/config/testing.json.example",
    "vendor/dropbox-client-ruby/lib/dropbox.rb",
    "vendor/dropbox-client-ruby/manifest",
    "vendor/dropbox-client-ruby/test/authenticator_test.rb",
    "vendor/dropbox-client-ruby/test/client_test.rb",
    "vendor/dropbox-client-ruby/test/util.rb"
  ]
  s.homepage = %q{http://github.com/kenpratt/dbox}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.1}
  s.summary = %q{Dropbox made easy.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

